name: Test

on: [push]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Dependencies
      run: make dep
    - name: Test
      run: make test
    - name: Test race
      run: make race
  release_linux:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Linux packages
      run: sudo apt update && sudo apt install -y upx-ucl
    - name: Build binary
      run: make buildlinux
    - name: Compress binary
      run: make compresslinux
    - name: Upload linux build
      uses: actions/upload-artifact@v1
      with:
        name: blchecker.linux
        path: ./blchecker.linux
    - name: Upload blacklist file
      uses: actions/upload-artifact@v1
      with:
        name: blacklist
        path: ./bl_list
  release_macos:
    needs: test
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install UPX
      run: brew update && brew install upx
    - name: Build binary
      run: make buildmacos
    - name: Upload macos build
      uses: actions/upload-artifact@v1
      with:
        name: blchecker.macos
        path: ./blchecker.macos